name: build distributions
run-name: ${{ github.actor }} is building
on:
  push:
    branches:
      - main
      - develop
jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: package
        run: mvn clean package
      - name: jlink
        run: jlink --no-header-files --compress=2 --strip-debug --add-modules ALL-MODULE-PATH --output target/JRE
      - name: jpackage
        run: jpackage --type deb --input target/ --main-jar cryodex-4.0.6-SNAPSHOT.jar --icon classes/main/resources/cryodex/icon.png --main-class cryodex.Main --runtime-image target/JRE/ --linux-shortcut --name cryodex
      - name: publish
        uses: actions/upload-artifact@v3
        with:
          name: linux-dist
          path: cryodex_*_amd64.deb
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: package
        run: mvn clean package
      - name: jlink
        run: jlink --no-header-files --compress=2 --strip-debug --add-modules ALL-MODULE-PATH --output target/JRE
      - name: jpackage
        run: jpackage --type msi --input target/ --main-jar cryodex-4.0.6-SNAPSHOT.jar --icon classes/main/resources/cryodex/icon.png --main-class cryodex.Main --runtime-image target/JRE/ --name cryodex
      - name: publish
        uses: actions/upload-artifact@v3
        with:
          name: windows-dist
          path: cryodex-*.msi
  darwin:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: package
        run: mvn clean package
      - name: jlink
        run: jlink --no-header-files --compress=2 --strip-debug --add-modules ALL-MODULE-PATH --output target/JRE
      - name: jpackage
        run: jpackage --type dmg --input target/ --main-jar cryodex-4.0.6-SNAPSHOT.jar --icon classes/main/resources/cryodex/icon.png --main-class cryodex.Main --runtime-image target/JRE/ --name cryodex
      - name: publish
        uses: actions/upload-artifact@v3
        with:
          name: darwin-dist
          path: cryodex-*.dmg
