name: build distributions
run-name: ${{ github.actor }} is building
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: package
        run: mvn clean package
      - name: jlink
        run: jlink --no-header-files --compress=2 --strip-debug --add-modules ALL-MODULE-PATH --output target/JRE
      - name: jpackage
        run: jpackage --type deb --input target/ --main-jar cryodex-4.0.6-SNAPSHOT.jar --icon src/main/resources/cryodex/widget/logo2.jpg --main-class cryodex.Main --runtime-image target/JRE/ --linux-shortcut --name cryodex
